### PR TITLE
support custom user data on nodes

### PR DESCRIPTION
**Pull request by gpip**
This makes it easier to know which items were matched, e.g. tree.add(descriptor, 'abc'); assert tree.search(descriptor, 1)[0].user_data == 'abc'

### CODE REVIEW

**Comment by ryanfox** [comment]
What's the use case here?  Isn't the value of the node sufficient to determine what value you matched?

**Comment by gpip** [comment]
Maybe you're thinking about a situation where the identifier is the descriptor, but a) that's not guaranteed to be unique so it's common to use a different identifier, b) it's a bad index as it's a ~pseudorandom bitstring which results in not being a good field to be indexed. After a `tree.search` the only way to find the information about the nodes that matched would be to iterate over all the dataset and find the ones with the descriptors returned, it's very inefficient.

**Comment by ryanfox** [comment]
With respect to a), my thinking was that nodes with the same value are indistinguishable.  Sure, they're not unique, but why would you want them to be?  A 5 is a 5, in what scenario does it matter *which* 5 you got back?

I don't quite follow you on b) either - what are you indexing?  You have to look at the results at least *once*, so I'm not sure what improvement that would buy you.

**Comment by gpip** [comment]
When you run `tree.search(something, threshold)` you're not returning only nodes with the same value, otherwise there would be no point in using this data structure. You're returning information about nodes that are within the threshold, they are not necessarily exact duplicates.

Maybe you could tell me how you're using this package, I'm not seeing an useful way to use it without having at least some indicator that is able to relate the descriptor (a bit string) to an identifier. If you think this is not a good idea for your package, by all means don't do it and close this issue.

Let's say you have one million items, item 1, item 2, item 3, .... Each of these have an associated bit string, bitstring 1, bitstring 2, bitstring 3, .... Zero or more of these bitstrings are within a distance of 2 of another 10 bitstrings. So you do a search `tree.search(somebitstring, 2)` and you get a bunch of bitstrings back. How do you find out which items are related to those bitstrings? Currently, you have to iterate over your 1 million items to find it out. The proposal is that tree.search would return a node which contains some information to indicate that you got back items 99999, 812381, ....

**Comment by ryanfox** [comment]
> How do you find out which items are related to those bitstrings? Currently, you have to iterate over your 1 million items to find it out

A dict seems like a pretty good built-in way to do this.  Like this:

    >>> hashed_entries = {bitstring 1: [item 1, item 4, item 24601, ...],
                          bitstring 2: [item 99999, item 812381, ...],
                          etc, etc
                         }

    >>> tree.search(somebitstring, 2)
    [bitstring 2, bitstring 406, bitstring 10000, ...]

    >>> hashes[bitstring 2]
    [item 99999, item 812381, ...]

You had to iterate over your million items to get the bitstrings in the first place, so I think precomputing a dict of them is not likely a major performance hit.

**Comment by gpip** [comment]
That's fine if you want keep it this way. But do you think it's better, or even a good idea, to use bitstring as keys (which are pseudorandom) instead of simple integers? At least in my case, I have initial data sitting in a typical database which gets updated while the bktree is live. Items have a very simple and efficient index, an integer. The bitstrings are not used as an index because it's slower to index and search through pseudorandom indexes. I also don't want to keep a bitstring index outside of the bktree (in addition to the data already sitting in the database), as that increases the memory usage. But that's just me, I guess I'll close this, thanks for your time.

**Comment by ryanfox** [comment]
I got it now.  This is what I meant when I initially asked what your use case is.

> I have initial data sitting in a typical database which gets updated while the bktree is live. Items have a very simple and efficient index, an integer. The bitstrings are not used as an index because it's slower to index and search through pseudorandom indexes. I also don't want to keep a bitstring index outside of the bktree (in addition to the data already sitting in the database), as that increases the memory usage

I think we're using different terminology - a bitstring (as I've been using the term) *is* an integer.  They're different representations of the same value.  For example, `0xe == 0b1110 == 14`.  Does that not satisfy your requirements?

**Comment by gpip** [comment]
Sorry, yes it can be represented as an integer. It just happens that '0000000001000000000000000010000000000000000000000000000000000000' and '0000000000000000000000000010000000000000000000000000000000000000', which differ by 1 bit and can be represented as 18014535948435456 and 137438953472 is a poorer way to index the data related to it (e.g. 1 and 2). This library seems to consider the descriptors in a vacuum, while in practice I can't see it being used as something that can absolutely only store the descriptors themselves and not an indicator of what those descriptors refer to (which you have to build yourself externally, and duplicate/triplicate memory usage).

**Comment by ryanfox** [comment]
I compared the two versions of tagging a node and measured the memory used and time to build the data structures in question (windows 10, python 3.4):

```
# Node class as currently in master
from collections import defaultdict
import datetime

import bktree

start = datetime.datetime.now()
tree = bktree.Tree()
cache = defaultdict(list)

for i in range(1000000):
	tree.add(i)
	cache[i].append(str(i))

stop = datetime.datetime.now()
input('finished in {} ms.  Hit enter to proceed'.format((start - stop).microseconds / 1000))


# 699.0MB, 50ms
```

```
# Node class as in the PR
from collections import defaultdict
import datetime

import bktree

start = datetime.datetime.now()
tree = bktree.Tree()
cache = defaultdict(list)

for i in range(1000000):
	tree.add(i, str(i))

stop = datetime.datetime.now()
input('finished in {} ms.  Hit enter to proceed'.format((start - stop).microseconds / 1000))


# 726.3MB, 500ms
```


It appears using the Python builtins is an order of magnitude faster to build, and actually uses *less* memory.  Thanks for the feedback, but I'm going to keep `Node` as-is for now.

**Comment by gpip** [comment]
Uh.. that's a poor way to compare those for a few different reasons, but are you sure `(start - stop).microseconds` is not completely incorrect to measure the time taken?

```
>>> import time
>>> import datetime
>>> 
>>> for i in range(10):
...     a = datetime.datetime.now()
...     time.sleep(0.003)
...     b = datetime.datetime.now()
...     print((a - b).microseconds / 1000)
... 
988.991
989.617
988.307
987.697
988.017
989.91
987.83
989.248
989.448
987.467
```

I think you meant just `(b - a)`:

```
>>> import time
>>> import datetime
>>> 
>>> for i in range(10):
...     a = datetime.datetime.now()
...     time.sleep(0.003)
...     b = datetime.datetime.now()
...     print(b - a)
... 
0:00:00.003842
0:00:00.003663
0:00:00.003396
0:00:00.003122
0:00:00.003809
0:00:00.003086
0:00:00.003850
0:00:00.003049
0:00:00.003858
0:00:00.003790
```

Then on my machine both take around 13 seconds to insert those 1e6 entries between 0 and 999,999. This comparison doesn't take into account that an insertion happens only once for a given entry, and then many searches (followed by many lookups in your code) occurs.

**Comment by ryanfox** [comment]
You're right about the time difference.  I was thinking total microseconds, it's just the fraction apparently.  Time between the two looks like a wash, 9.8-9.9 vs 9.9-10.0 seconds on my machine.

Lookups, though - I didn't time it, but Python set lookups are O(1).  It also appears to use less memory.  I'm hesitant to add something when the standard library performs at least as well on both time and space.

**Comment by gpip** [comment]
That's fine, no worries. btw, if you want to reduce the memory usage you could use `__slots__` for the node class you have there.

**Pull request closed without merging**
